// <auto-generated />
using System;
using InstaHub_MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InstaHub_MVC.Migrations
{
    [DbContext(typeof(InstaHubDbContext))]
    [Migration("20190312185639_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InstaHub_MVC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<bool>("Online");

                    b.HasKey("UserID");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("InstaHub_MVC.Models.Contact", b =>
                {
                    b.Property<string>("UserID");

                    b.Property<int>("ContactID");

                    b.HasKey("UserID", "ContactID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("InstaHub_MVC.Models.Hub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HubType");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Hubs");
                });

            modelBuilder.Entity("InstaHub_MVC.Models.Message", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<int>("HubID");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("UserID");

                    b.HasKey("ID");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("InstaHub_MVC.Models.UserHubs", b =>
                {
                    b.Property<string>("UserID");

                    b.Property<int>("HubID");

                    b.HasKey("UserID", "HubID");

                    b.ToTable("UserHubs");
                });
#pragma warning restore 612, 618
        }
    }
}
